# vim: set softtabstop=2 tabstop=2 shiftwidth=2 expandtab autoindent smartindent syntax=yaml:

- hosts: consul_servers
  tasks:
    - name: ansible-trust-dns
      include_role:
        name: ansible-trust-dns
  tags:
    - trust

- hosts: consul_servers
  tasks:
    # https://www.elastic.co/guide/en/elasticsearch/reference/6.8/vm-max-map-count.html
    - name: "Set vm.max_map_count to support Elasticsearch workloads"
      command: sysctl -w vm.max_map_count=262144

- hosts: consul_servers
  vars_files:
    - vars/consul-server.yaml
      #@roles:
      #@  - consul
  tasks:
    - name: consul
      include_role:
        name: consul
  tags:
    - consul

#- hosts: all
#  vars_files:
#    - vars/main.yaml
#  tasks:
#    - name: vault
#      include_role:
#        name: vault
#  tags:
#    - vault

- hosts: all
  tasks:
    - name: docker
      include_role:
        name: docker
  tags:
    - docker

- hosts: all
  vars_files:
    - vars/main.yaml
  tasks:
    - name: nomad
      include_role:
        name: nomad
  tags:
    - nomad
